---
name: "Auto Parental Tags"
guid: "eb5d7894-8eef-4b36-aa6f-5d124e828ce1"
version: "0.1.0"
targetAbi: "10.11.5.0"
framework: "net9.0"
overview: "Automatically tag movies with target audience using AI"
description: >
  Uses AI (Google Gemini, OpenAI, or LocalAI) to analyze movie metadata and automatically add audience target tags (kids, teens, adults). Considers target audience rather than just content ratings.

category: "Metadata"
owner: "benklop"
artifacts:
  - "Jellyfin.Plugin.AutoParentalTags.dll"
changelog: |-
  - Refactor changelog workflow to inherit secrets instead of specifying … (@benklop) (#9)
  - Add release instructions and fix version formatting in workflows (@benklop) (#7)
  - Prepare for release v0.1.0 (@[github-actions[bot]](https://github.com/apps/github-actions)) (#5)
  - Fix build failure (@benklop) (#4)
  - Prepare for release v0.1.0 (@[github-actions[bot]](https://github.com/apps/github-actions)) (#2)
  - Add comprehensive Copilot instructions for Auto Parental Tags plugin (@benklop) (#1)
